### PR TITLE
make a basic and working deskboard

### PR DESCRIPTION
**Pull request by felipemarinho97**

### CODE REVIEW

**Comment by axelmedeiros** [comment]
@felipemarinho97 has a CORS error in the project!


captura de tela de 2018-11-01 13-21-07

**Review by axelmedeiros — CHANGES_REQUESTED** [review]
has a CORS error in the project!

**Comment by felipemarinho97** [comment]
@axelmedeiros I was having the same problem due to not being in the UFCG network. Did you started the backend using `npm run dev` ?

**Comment by axelmedeiros** [comment]
I'm sorry, I rode an earlier version of the backend

**Pull request merged**
